name: Generate Salt Extensions Index

on:
  schedule:
    # Every day at 1:30 UTC
    - cron: "30 1 * * *"
  push:
    branches: [ main ]

jobs:

  salt-ext-tidx1-Linux:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version:
          - 3.5
          - 3.6
          - 3.7
          - 3.8
        salt-version:
          - 3001.3
          - 3002.1

    steps:
      - name: Define Results Directory
        run: |
          echo "RESULTS_DIR=.cache/${{ matrix.salt-version }}/${{ runner.os }}/${{ matrix.python-version }}" >> $GITHUB_ENV

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download And Extract salt-ext-tidx1
        run: |
          mkdir pkg
          cd pkg
          curl -Ls https://files.pythonhosted.org/packages/ac/87/dfc305270f1ae5ff2044ce178f7e244c511e7c1923675d3e4715968969ca/salt-ext-tidx1-1.2.3.tar.gz | tar zxvf - --strip 1
          ls -lah

      - name: Install Nox
        run: |
          python -m pip install --upgrade pip
          pip install nox

      - name: Test
        env:
          SALT_REQUIREMENT: salt==${{ matrix.salt-version }}
        run: |
          cd pkg
          nox --force-color -e tests-3 -- -vv tests/

      - name: Store Job Status
        if: ${{ always() }}
        run: |
          mkdir -p ${{ env.RESULTS_DIR }}
          echo https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}??check_suite_focus=true > ${{ env.RESULTS_DIR }}/url
          echo ${{ job.status }} > ${{ env.RESULTS_DIR }}/status

      - name: Upload Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: salt-ext-tidx1
          path: .cache
  salt-ext-tidx1-macOS:
    runs-on: macOS-latest
    continue-on-error: true

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version:
          - 3.5
          - 3.6
          - 3.7
          - 3.8
        salt-version:
          - 3001.3
          - 3002.1

    steps:
      - name: Define Results Directory
        run: |
          echo "RESULTS_DIR=.cache/${{ matrix.salt-version }}/${{ runner.os }}/${{ matrix.python-version }}" >> $GITHUB_ENV

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download And Extract salt-ext-tidx1
        run: |
          mkdir pkg
          cd pkg
          curl -Ls https://files.pythonhosted.org/packages/ac/87/dfc305270f1ae5ff2044ce178f7e244c511e7c1923675d3e4715968969ca/salt-ext-tidx1-1.2.3.tar.gz | tar zxvf - --strip 1
          ls -lah

      - name: Install Nox
        run: |
          python -m pip install --upgrade pip
          pip install nox

      - name: Test
        env:
          SALT_REQUIREMENT: salt==${{ matrix.salt-version }}
        run: |
          cd pkg
          nox --force-color -e tests-3 -- -vv tests/

      - name: Store Job Status
        if: ${{ always() }}
        run: |
          mkdir -p ${{ env.RESULTS_DIR }}
          echo https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}??check_suite_focus=true > ${{ env.RESULTS_DIR }}/url
          echo ${{ job.status }} > ${{ env.RESULTS_DIR }}/status

      - name: Upload Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: salt-ext-tidx1
          path: .cache
  salt-ext-tidx1-Windows:
    runs-on: windows-latest
    continue-on-error: true

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version:
          - 3.5
          - 3.6
          - 3.7
          - 3.8
        salt-version:
          - 3001.3
          - 3002.1

    steps:
      - name: Define Results Directory
        shell: bash
        run: |
          echo "RESULTS_DIR=.cache/${{ matrix.salt-version }}/${{ runner.os }}/${{ matrix.python-version }}" >> $GITHUB_ENV

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download And Extract salt-ext-tidx1
        shell: bash
        run: |
          mkdir pkg
          cd pkg
          curl -Ls https://files.pythonhosted.org/packages/ac/87/dfc305270f1ae5ff2044ce178f7e244c511e7c1923675d3e4715968969ca/salt-ext-tidx1-1.2.3.tar.gz | tar zxvf - --strip 1
          ls -lah

      - name: Install Nox
        run: |
          python -m pip install --upgrade pip
          pip install nox

      - name: Test
        env:
          SALT_REQUIREMENT: salt==${{ matrix.salt-version }}
          EXTRA_REQUIREMENTS_INSTALL: Cython
        run: |
          cd pkg
          nox --force-color -e tests-3 -- -vv tests/

      - name: Store Job Status
        shell: bash
        if: ${{ always() }}
        run: |
          mkdir -p ${{ env.RESULTS_DIR }}
          echo https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}??check_suite_focus=true > ${{ env.RESULTS_DIR }}/url
          echo ${{ job.status }} > ${{ env.RESULTS_DIR }}/status

      - name: Upload Results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: salt-ext-tidx1
          path: .cache

  Generate-Extensions-Index:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - salt-ext-tidx1-Linux
      - salt-ext-tidx1-macOS
      - salt-ext-tidx1-Windows

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set PIP Cache Key
        run: echo "PY=$(python --version --version | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Restore PIP cache
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}|pip-docs|${{ env.PY }}|${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}|pip-docs|${{ env.PY }}|${{ hashFiles('requirements/*.txt') }}
            ${{ runner.os }}|pip-docs|${{ env.PY }}|

      - name: Install Requirements
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements/base.txt
          python -m pip install -r requirements/docs.txt

      - name: Setup Packages Information Cache
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: .cache
          key: salt-extensions-cache-${{ hashFiles('.state/*') }}
          restore_keys: |
            salt-extensions-cache-${{ hashFiles('.state/*') }}
            salt-extensions-cache

      - name: Download Results
        uses: actions/download-artifact@v2
        with:
          path: results

      - name: Generate Index
        env:
          LOCAL_CACHE_PATH: .cache
        run: |
          find .cache -print
          find results -print
          echo "---"
          python scripts/generate-docs-index.py
          cd docs
          make html
          cp -Rp _build/html extensions-index

      - name: Upload Generated HTML Index
        uses: actions/upload-artifact@v2
        with:
          name: extensions-index-html
          path: docs/_build/html

  Publish-Extensions-Index:
    runs-on: ubuntu-latest
    needs:
      - Generate-Extensions-Index

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          persist-credentials: false
          fetch-depth: 0

      - name: Download Generated HTML Index
        uses: actions/download-artifact@v2
        with:
          path: generated-html
          name: extensions-index-html

      - name: Update Extensions Index HTML
        run: |
          ls -lah generated-html
          find . -not -name ".git*" -not -name generated-html -not -name CNAME -maxdepth 1 -exec rm -rf {} \;
          cp -Rp generated-html/* .
          rm -rf generated-html
          mv _static static
          sed -i 's/_static/static/g' *.html
          git add .

      - name: Commit updated extensions index
        uses: actions-js/push@v1.2
        with:
          branch: gh-pages
          message: Update Extensions Index
          github_token: ${{ secrets.GITHUB_TOKEN }}
